/**
 * Dementia Condition Module — calibration layer for SolenOS.
 *
 * This module configures vocabulary, attention weighting, and evaluation
 * cases for dementia care contexts. It does NOT replace DARE or normalization.
 * It influences extraction classification and downstream attention scoring.
 */

import type { ConditionModule } from "./types";

const DEMENTIA_VOCABULARY: ConditionModule["vocabulary"] = [
  {
    id: "dementia_cognition_confusion",
    patterns: [
      /\b(confus\w*|disorient\w*|doesn't know where\b|doesn't know who\b|lost\b)/i,
    ],
    target_type: "symptom_observed",
    domain: "cognition",
    low_specificity: false,
    preserve_ambiguity: true,
    safety_relevance: 0.3,
    attention_weight: 1.4,
    forbidden_inferences: ["dementia progression", "stage change", "delirium diagnosis"],
  },
  {
    id: "dementia_cognition_repeated_questions",
    patterns: [
      /\b(asked.*same.*(?:question|again|multiple times|like \d+ times)|keeps asking|repeatedly asks|asking again)\b/i,
    ],
    target_type: "symptom_observed",
    domain: "cognition",
    low_specificity: false,
    preserve_ambiguity: false,
    safety_relevance: 0.1,
    attention_weight: 1.2,
    forbidden_inferences: ["memory deterioration diagnosis", "dementia stage assessment"],
  },
  {
    id: "dementia_cognition_word_finding",
    patterns: [
      /\b(can't find the word|word.?finding|trouble finding words|struggles to say|can't remember the word)\b/i,
    ],
    target_type: "symptom_observed",
    domain: "cognition",
    low_specificity: false,
    preserve_ambiguity: false,
    safety_relevance: 0.1,
    attention_weight: 1.1,
    forbidden_inferences: ["aphasia diagnosis", "dementia progression"],
  },
  {
    id: "dementia_cognition_conversation",
    patterns: [
      /\b(can't.*follow|difficulty following|trouble following|lost track of conversation|doesn't understand)\b/i,
    ],
    target_type: "symptom_observed",
    domain: "cognition",
    low_specificity: false,
    preserve_ambiguity: true,
    safety_relevance: 0.1,
    attention_weight: 1.2,
    forbidden_inferences: ["hearing loss diagnosis", "cognitive decline diagnosis"],
  },
  {
    id: "dementia_behavior_agitation",
    patterns: [
      /\b(agitat\w*|aggressive|yelling|screaming|resist\w* care|refuses care|combative)\b/i,
    ],
    target_type: "symptom_observed",
    domain: "behavior",
    low_specificity: false,
    preserve_ambiguity: false,
    safety_relevance: 0.6,
    attention_weight: 1.5,
    forbidden_inferences: ["behavioral disorder diagnosis", "delirium diagnosis"],
  },
  {
    id: "dementia_behavior_withdrawal",
    patterns: [
      /\b(withdrawn|withdrawing|isolating|won't talk|stopped talking|no longer engages|disengaged)\b/i,
    ],
    target_type: "symptom_observed",
    domain: "behavior",
    low_specificity: true,
    preserve_ambiguity: true,
    safety_relevance: 0.2,
    attention_weight: 1.2,
    forbidden_inferences: ["depression diagnosis", "dementia progression"],
  },
  {
    id: "dementia_behavior_apathy",
    patterns: [
      /\b(apathetic|apathy|no interest|doesn't care|unmotivated|flat affect)\b/i,
    ],
    target_type: "symptom_observed",
    domain: "behavior",
    low_specificity: true,
    preserve_ambiguity: true,
    safety_relevance: 0.2,
    attention_weight: 1.1,
    forbidden_inferences: ["depression diagnosis", "dementia stage assessment"],
  },
  {
    id: "dementia_behavior_nighttime",
    patterns: [
      /\b(sundowning|sundown|nighttime|night.?time|waking up.*(?:night|2am|3am|4am)|wandering.*night|up all night)\b/i,
    ],
    target_type: "symptom_observed",
    domain: "behavior",
    low_specificity: false,
    preserve_ambiguity: false,
    safety_relevance: 0.5,
    attention_weight: 1.4,
    forbidden_inferences: ["sundowning syndrome diagnosis", "sleep disorder diagnosis"],
  },
  {
    id: "dementia_behavior_routine",
    patterns: [
      /\b(routine.*disrupt|disrupt.*routine|can't stick to routine|off schedule|out of routine)\b/i,
    ],
    target_type: "symptom_observed",
    domain: "behavior",
    low_specificity: true,
    preserve_ambiguity: true,
    safety_relevance: 0.2,
    attention_weight: 1.1,
    forbidden_inferences: ["dementia progression", "behavioral disorder diagnosis"],
  },
  {
    id: "dementia_safety_fall",
    patterns: [
      /\b(fell|fall|fallen|tripped|slipped|tumbled)\b/i,
    ],
    target_type: "incident_occurred",
    domain: "safety",
    low_specificity: false,
    preserve_ambiguity: false,
    safety_relevance: 0.95,
    attention_weight: 1.8,
    forbidden_inferences: ["fragility diagnosis", "mobility disorder diagnosis"],
  },
  {
    id: "dementia_safety_wandering",
    patterns: [
      /\b(wander\w*|got lost|couldn't find.*way back|left.*house|door.*open|missing)\b/i,
    ],
    target_type: "incident_occurred",
    domain: "safety",
    low_specificity: false,
    preserve_ambiguity: false,
    safety_relevance: 0.9,
    attention_weight: 1.8,
    forbidden_inferences: ["elopement diagnosis", "severe dementia assessment"],
  },
  {
    id: "dementia_safety_medication",
    patterns: [
      /\b(missed.*medication|doubled.*medication|wrong dose|forgot.*meds|medication error)\b/i,
    ],
    target_type: "medication_changed",
    domain: "safety",
    low_specificity: false,
    preserve_ambiguity: false,
    safety_relevance: 0.85,
    attention_weight: 1.7,
    forbidden_inferences: ["medication noncompliance diagnosis", "cognitive impairment diagnosis"],
  },
  {
    id: "dementia_safety_appliance",
    patterns: [
      /\b(stove.*(?:off|left|unattended|burner.*left|oven.*left)|appliance.*left|unsafe|cooking.*concern)\b/i,
    ],
    target_type: "incident_occurred",
    domain: "safety",
    low_specificity: false,
    preserve_ambiguity: false,
    safety_relevance: 0.9,
    attention_weight: 1.7,
    forbidden_inferences: ["unsafe to live alone diagnosis", "incapacity determination"],
  },
  {
    id: "dementia_safety_driving",
    patterns: [
      /\b(driving.*concern|stopped driving|won't drive|confused.*driving|got lost.*driving)\b/i,
    ],
    target_type: "symptom_observed",
    domain: "safety",
    low_specificity: false,
    preserve_ambiguity: true,
    safety_relevance: 0.8,
    attention_weight: 1.5,
    forbidden_inferences: ["unsafe driver determination", "license revocation recommendation"],
  },
  {
    id: "dementia_function_adl",
    patterns: [
      /\b(bathing|dressing|getting dressed|eating|walking|mobility|toileting|cooking|household tasks|medication self)\b/i,
    ],
    target_type: "symptom_observed",
    domain: "function",
    low_specificity: true,
    preserve_ambiguity: true,
    safety_relevance: 0.4,
    attention_weight: 1.2,
    forbidden_inferences: ["ADL decline diagnosis", "functional staging assessment"],
  },
  {
    id: "dementia_function_familiar_task",
    patterns: [
      /\b(can't.*(?:cook|clean|dress|bathe)|no longer able|inability)\b/i,
    ],
    target_type: "symptom_observed",
    domain: "function",
    low_specificity: true,
    preserve_ambiguity: true,
    safety_relevance: 0.3,
    attention_weight: 1.3,
    forbidden_inferences: ["functional decline diagnosis", "dementia progression"],
  },
  {
    id: "dementia_caregiver_burden",
    patterns: [
      /\b(caregiver.*(?:exhaust|burden|overwhelm|tired|stress|burnt out)|I'm exhausted|I can't do this|burnt out)\b/i,
    ],
    target_type: "symptom_observed",
    domain: "care_system",
    low_specificity: true,
    preserve_ambiguity: true,
    safety_relevance: 0.5,
    attention_weight: 1.3,
    forbidden_inferences: ["caregiver incapacity diagnosis", "placement recommendation"],
  },
  {
    id: "dementia_medication_change",
    patterns: [
      /\b(started.*medication|stopped.*medication|changed.*medication|new.*prescription|dose.*changed)\b/i,
    ],
    target_type: "medication_changed",
    domain: "medication",
    low_specificity: false,
    preserve_ambiguity: false,
    safety_relevance: 0.7,
    attention_weight: 1.4,
    forbidden_inferences: ["treatment recommendation", "medication efficacy assessment"],
  },
  {
    id: "dementia_appointment_outcome",
    patterns: [
      /\b(neurologist|geriatrician|appointment|follow.?up|doctor.*visit|specialist)\b/i,
    ],
    target_type: "appointment_occurred",
    domain: "care_system",
    low_specificity: false,
    preserve_ambiguity: false,
    safety_relevance: 0.2,
    attention_weight: 1.1,
    forbidden_inferences: ["diagnosis confirmation", "prognosis statement"],
  },
  {
    id: "dementia_global_status_good_day",
    patterns: [
      /\b(good day|bad day|not herself|not himself|seems off|seems different)\b/i,
    ],
    target_type: "symptom_observed",
    domain: "cognition",
    low_specificity: true,
    preserve_ambiguity: true,
    safety_relevance: 0.1,
    attention_weight: 1.0,
    forbidden_inferences: ["dementia progression", "depression diagnosis", "delirium diagnosis"],
  },
  {
    id: "dementia_question_stage",
    patterns: [
      /\b(how far along|what stage|stage of dementia|how advanced|progression)\b/i,
    ],
    target_type: "symptom_observed",
    domain: "cognition",
    low_specificity: true,
    preserve_ambiguity: true,
    safety_relevance: 0.0,
    attention_weight: 0.9,
    forbidden_inferences: ["dementia staging", "prognosis", "disease progression prediction"],
  },
];

const DEMENTIA_ATTENTION_WEIGHTS: ConditionModule["attention_weights"] = [
  {
    domain: "cognition",
    urgency_delta: 5,
    uncertainty_delta: 3,
    attention_multiplier: 1.2,
    condition: "new",
  },
  {
    domain: "cognition",
    urgency_delta: 10,
    uncertainty_delta: 5,
    attention_multiplier: 1.4,
    condition: "escalating",
  },
  {
    domain: "behavior",
    urgency_delta: 8,
    uncertainty_delta: 4,
    attention_multiplier: 1.3,
    condition: "new",
  },
  {
    domain: "behavior",
    urgency_delta: 15,
    uncertainty_delta: 8,
    attention_multiplier: 1.6,
    condition: "escalating",
  },
  {
    domain: "safety",
    urgency_delta: 20,
    uncertainty_delta: 5,
    attention_multiplier: 1.8,
    condition: "new",
  },
  {
    domain: "safety",
    urgency_delta: 25,
    uncertainty_delta: 10,
    attention_multiplier: 2.0,
    condition: "escalating",
  },
  {
    domain: "function",
    urgency_delta: 10,
    uncertainty_delta: 5,
    attention_multiplier: 1.3,
    condition: "materially_different",
  },
  {
    domain: "care_system",
    urgency_delta: 5,
    uncertainty_delta: 3,
    attention_multiplier: 1.1,
    condition: "safety_associated",
  },
];

const DEMENTIA_EVALUATION_CASES: ConditionModule["evaluation_cases"] = [
  {
    id: "dementia_001",
    input: "She asked me the same question like 5 times today.",
    expected_domain: "cognition",
    expected_atomic_type: "symptom_observed",
    expected_entity_type: "person",
    expected_confidence_tag: "confirmed",
    expected_source_pointer: true,
    expected_clinical_boundary_compliant: true,
    notes: "Repeated questions map to cognition observation, not memory deterioration diagnosis.",
  },
  {
    id: "dementia_002",
    input: "Mom wandered out the front door again last night.",
    expected_domain: "safety",
    expected_atomic_type: "incident_occurred",
    expected_entity_type: "person",
    expected_confidence_tag: "confirmed",
    expected_source_pointer: true,
    expected_clinical_boundary_compliant: true,
    notes: "Wandering is a safety-related behavior, not automatically an emergency.",
  },
  {
    id: "dementia_003",
    input: "She's not herself today but I can't really explain why.",
    expected_domain: "cognition",
    expected_atomic_type: "symptom_observed",
    expected_entity_type: "person",
    expected_confidence_tag: "reported",
    expected_source_pointer: true,
    expected_clinical_boundary_compliant: true,
    notes: "'Not herself' is intentionally ambiguous — extract as observation with uncertainty.",
  },
  {
    id: "dementia_004",
    input: "She gets really agitated around 6pm lately.",
    expected_domain: "behavior",
    expected_atomic_type: "symptom_observed",
    expected_entity_type: "person",
    expected_confidence_tag: "confirmed",
    expected_source_pointer: true,
    expected_clinical_boundary_compliant: true,
    notes: "Agitation is a direct behavior observation.",
  },
  {
    id: "dementia_005",
    input: "She can't seem to follow the TV shows she used to love.",
    expected_domain: "cognition",
    expected_atomic_type: "symptom_observed",
    expected_entity_type: "person",
    expected_confidence_tag: "reported",
    expected_source_pointer: true,
    expected_clinical_boundary_compliant: true,
    notes: "Conversation/TV following difficulty is cognition observation.",
  },
  {
    id: "dementia_006",
    input: "PT said she needs more help getting dressed.",
    expected_domain: "function",
    expected_atomic_type: "symptom_observed",
    expected_entity_type: "person",
    expected_confidence_tag: "reported",
    expected_source_pointer: true,
    expected_clinical_boundary_compliant: true,
    notes: "PT observation is reported, not a functional decline diagnosis.",
  },
  {
    id: "dementia_007",
    input: "She forgot to turn the stove off again.",
    expected_domain: "safety",
    expected_atomic_type: "incident_occurred",
    expected_entity_type: "person",
    expected_confidence_tag: "confirmed",
    expected_source_pointer: true,
    expected_clinical_boundary_compliant: true,
    notes: "Safety observation with exact evidence.",
  },
  {
    id: "dementia_008",
    input: "How far along is her dementia now?",
    expected_domain: "cognition",
    expected_atomic_type: "symptom_observed",
    expected_entity_type: "person",
    expected_confidence_tag: "reported",
    expected_source_pointer: true,
    expected_clinical_boundary_compliant: true,
    notes: "Caregiver question about staging — must not generate dementia stage assessment.",
  },
  {
    id: "dementia_009",
    input: "She had a really good day today.",
    expected_domain: "cognition",
    expected_atomic_type: "symptom_observed",
    expected_entity_type: "person",
    expected_confidence_tag: "reported",
    expected_source_pointer: true,
    expected_clinical_boundary_compliant: true,
    notes: "Low-specificity global status observation.",
  },
  {
    id: "dementia_010",
    input: "She keeps waking up around 2am and trying to leave the house.",
    expected_domain: "behavior",
    expected_atomic_type: "symptom_observed",
    expected_entity_type: "person",
    expected_confidence_tag: "confirmed",
    expected_source_pointer: true,
    expected_clinical_boundary_compliant: true,
    notes: "Nighttime behavior with safety relevance.",
  },
];

export const DEMENTIA_MODULE: ConditionModule = {
  id: "dementia",
  label: "Dementia Care",
  vocabulary: DEMENTIA_VOCABULARY,
  attention_weights: DEMENTIA_ATTENTION_WEIGHTS,
  evaluation_cases: DEMENTIA_EVALUATION_CASES,
  forbidden_clinical_inferences: [
    "dementia staging",
    "progression diagnosis",
    "prognosis",
    "treatment recommendations",
    "medication changes",
    "diagnostic conclusions",
    "claims that a behavior definitively represents a particular disease process",
    "delirium diagnosis",
    "depression diagnosis",
    "fragility diagnosis",
    "mobility disorder diagnosis",
    "unsafe to live alone diagnosis",
    "caregiver incapacity diagnosis",
    "placement recommendation",
    "license revocation recommendation",
    "functional decline diagnosis",
    "behavioral disorder diagnosis",
    "aphasia diagnosis",
    "hearing loss diagnosis",
    "cognitive decline diagnosis",
    "memory deterioration diagnosis",
    "medication noncompliance diagnosis",
    "sundowning syndrome diagnosis",
    "sleep disorder diagnosis",
    "elopement diagnosis",
    "severe dementia assessment",
    "dementia stage assessment",
  ],
  requires_clinical_confirmation: true,
};
